---
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{github.repository}}-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - run: docker compose run --rm app lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - run: docker compose run --rm app test
  keep-alive:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
